import { Course, CareerRole, RoadmapNode, Project, Resource, StudyTask, Achievement } from './types';

export const COURSES: Course[] = [
  {
    id: 'cse',
    slug: 'cse',
    name: 'Computer Science Engineering',
    shortName: 'CSE',
    description: 'Master software development, algorithms, system architecture, cloud platforms, and modern AI technologies.',
    icon: '💻',
    subjects: ['Data Structures & Algorithms', 'Operating Systems', 'Database Management', 'Computer Networks', 'Software Engineering', 'Object-Oriented Programming'],
    skills: ['Programming (Java/Python/C++)', 'Web Development', 'SQL & Databases', 'Git & GitHub', 'System Design Basics', 'Problem Solving'],
    domains: ['Software Development', 'Data & AI', 'Cloud & DevOps', 'Cybersecurity', 'Mobile Development', 'Database Administration', 'Testing & QA'],
    careerCount: 8,
  },
  {
    id: 'aiml',
    slug: 'aiml',
    name: 'Artificial Intelligence & Machine Learning',
    shortName: 'AIML',
    description: 'Focus on intelligent agents, deep learning neural networks, natural language processing, computer vision, and predictive analytics.',
    icon: '🧠',
    subjects: ['Linear Algebra & Probability', 'Machine Learning Foundations', 'Deep Learning', 'Natural Language Processing', 'Computer Vision', 'Data Mining'],
    skills: ['Python', 'NumPy & Pandas', 'Scikit-learn', 'PyTorch & TensorFlow', 'Model Evaluation', 'Data Preprocessing'],
    domains: ['Machine Learning', 'Data Science', 'Generative AI', 'Computer Vision', 'NLP', 'Data Analytics'],
    careerCount: 6,
  },
  {
    id: 'it',
    slug: 'it',
    name: 'Information Technology',
    shortName: 'IT',
    description: 'Apply computing technology to business needs, networking infrastructure, enterprise web applications, and security systems.',
    icon: '🌐',
    subjects: ['Network Administration', 'Web Technologies', 'Information Security', 'Cloud Computing', 'Database Systems', 'Enterprise Software'],
    skills: ['Full Stack Development', 'Linux Administration', 'Network Configuration', 'Cloud Services (AWS/Azure)', 'API Integration'],
    domains: ['Web Development', 'Cloud & DevOps', 'Cybersecurity', 'IT Support & Systems', 'Database Systems'],
    careerCount: 7,
  },
  {
    id: 'ece',
    slug: 'ece',
    name: 'Electronics & Communication Engineering',
    shortName: 'ECE',
    description: 'Bridge hardware and software with embedded systems, microcontrollers, IoT devices, signal processing, and robotics.',
    icon: '⚡',
    subjects: ['Microprocessors & Microcontrollers', 'Signals & Systems', 'VLSI Design', 'Digital Electronics', 'IoT Architecture', 'Embedded C'],
    skills: ['Embedded C / C++', 'Microcontroller Programming (Arduino/STM32/ESP32)', 'Circuit Design', 'IoT Protocols (MQTT/HTTP)', 'Firmware Testing'],
    domains: ['Embedded Systems', 'IoT Engineering', 'Robotics', 'VLSI Design', 'Hardware Testing', 'Firmware Development'],
    careerCount: 5,
  },
  {
    id: 'eee',
    slug: 'eee',
    name: 'Electrical & Electronics Engineering',
    shortName: 'EEE',
    description: 'Power systems, electrical machines, power electronics, renewable energy, automation, and industrial control systems.',
    icon: '🔋',
    subjects: ['Power Systems', 'Control Systems', 'Power Electronics', 'Renewable Energy', 'PLC & SCADA', 'Electrical Machines'],
    skills: ['MATLAB / Simulink', 'PLC Programming', 'Circuit Simulation', 'Power System Analysis', 'Industrial Automation'],
    domains: ['Power Systems', 'Industrial Automation', 'Electric Vehicles', 'Embedded IoT', 'Renewable Energy'],
    careerCount: 4,
  },
  {
    id: 'mechanical',
    slug: 'mechanical',
    name: 'Mechanical Engineering',
    shortName: 'Mechanical',
    description: 'Design, manufacturing, thermal analysis, CAD/CAM modeling, robotics, and emerging simulation technologies.',
    icon: '⚙️',
    subjects: ['Thermodynamics', 'Strength of Materials', 'Machine Design', 'Fluid Mechanics', 'CAD/CAM', 'Manufacturing Processes'],
    skills: ['SolidWorks / AutoCAD', 'ANSYS / FEA Simulation', 'Python for Engineers', 'Robotics Basics', 'Product Design'],
    domains: ['Design & CAD Engineering', 'Robotics & Automation', 'Computational Mechanics', 'Manufacturing & QA'],
    careerCount: 4,
  },
  {
    id: 'civil',
    slug: 'civil',
    name: 'Civil Engineering',
    shortName: 'Civil',
    description: 'Infrastructure planning, structural engineering, surveying, GIS mapping, project management, and construction technology.',
    icon: '🏗️',
    subjects: ['Structural Analysis', 'Geotechnical Engineering', 'Surveying & GIS', 'Concrete Technology', 'Transportation Engineering'],
    skills: ['AutoCAD Civil 3D', 'STAAD Pro / ETABS', 'Revit BIM', 'Project Estimation', 'GIS Mapping Tools'],
    domains: ['Structural Engineering', 'BIM Modeling', 'GIS Analysis', 'Project Management'],
    careerCount: 4,
  },
  {
    id: 'bca',
    slug: 'bca',
    name: 'Bachelor of Computer Applications',
    shortName: 'BCA',
    description: 'Comprehensive software applications, modern web programming, database operations, and practical app development.',
    icon: '📱',
    subjects: ['Programming in C/Java/Python', 'Web Technologies (HTML/CSS/JS)', 'Database Management', 'Software Engineering', 'Mobile App Dev'],
    skills: ['JavaScript & React', 'Node.js / Express', 'MySQL / MongoDB', 'Git & GitHub', 'Responsive UI Design'],
    domains: ['Frontend Development', 'Full Stack Development', 'Software QA', 'Mobile Development', 'Technical Support'],
    careerCount: 6,
  },
  {
    id: 'bsc-cs',
    slug: 'bsc-cs',
    name: 'B.Sc Computer Science',
    shortName: 'B.Sc CS',
    description: 'Theoretical computing principles, software development, data structures, scientific computing, and statistical analysis.',
    icon: '🔬',
    subjects: ['Discrete Mathematics', 'Data Structures', 'Database Systems', 'Computer Architecture', 'Object-Oriented Programming'],
    skills: ['Python / Java', 'SQL', 'Data Analysis', 'Web Programming', 'Algorithmic Problem Solving'],
    domains: ['Software Development', 'Data Analysis', 'Web Development', 'QA Testing'],
    careerCount: 5,
  },
];

export const CAREER_ROLES: CareerRole[] = [
  {
    id: 'full-stack-developer',
    slug: 'full-stack-developer',
    courseSlug: 'cse',
    title: 'Full Stack Developer',
    domain: 'Software Development',
    description: 'Full Stack Developers build both the user interface (frontend) and server logic, database interactions, and APIs (backend) of web applications.',
    beginnerSummary: 'You build entire websites and web apps from what the user clicks on screen to how data gets saved in the database.',
    difficulty: 'Intermediate',
    mainSkills: ['HTML/CSS/JavaScript', 'React or Next.js', 'Node.js & Express', 'SQL & NoSQL Databases', 'RESTful APIs', 'Git & GitHub', 'Deployment'],
    technologies: ['React', 'Next.js', 'Node.js', 'Express', 'PostgreSQL', 'MongoDB', 'Tailwind CSS', 'Docker', 'Vercel'],
    responsibilities: [
      'Design clean, responsive user interfaces that work across devices',
      'Build server-side logic and connect frontend to databases via REST or GraphQL APIs',
      'Model and optimize database schemas for fast queries',
      'Implement user authentication and role-based security',
      'Deploy, monitor, and maintain production web applications',
    ],
    beginnerReqs: [
      'Basic curiosity for how websites work',
      'No prior degree or coding experience required to start',
      'Computer with any modern operating system and internet access',
    ],
    roadmapShUrl: 'https://roadmap.sh/full-stack',
    isPopular: true,
  },
  {
    id: 'frontend-developer',
    slug: 'frontend-developer',
    courseSlug: 'cse',
    title: 'Frontend Developer',
    domain: 'Software Development',
    description: 'Frontend Developers craft the visual, interactive experiences people see and interact with in web and mobile browsers.',
    beginnerSummary: 'You turn visual designs into interactive, accessible websites using HTML, CSS, JavaScript, and React.',
    difficulty: 'Beginner',
    mainSkills: ['HTML5 & Semantic Markup', 'CSS3 & Tailwind CSS', 'JavaScript (ES6+)', 'React / Vue', 'Responsive Design', 'API Integration'],
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'TypeScript', 'React', 'Tailwind CSS', 'Vite', 'Git'],
    responsibilities: [
      'Convert UI/UX wireframes into functional web pages',
      'Ensure high performance, responsiveness, and cross-browser compatibility',
      'Manage client state and consume backend REST APIs',
      'Optimize web vitals, accessibility (a11y), and SEO standards',
    ],
    beginnerReqs: ['Visual eye for detail', 'Basic computer literacy', 'Patience with styling and debugging UI'],
    roadmapShUrl: 'https://roadmap.sh/frontend',
    isPopular: true,
  },
  {
    id: 'backend-developer',
    slug: 'backend-developer',
    courseSlug: 'cse',
    title: 'Backend Developer',
    domain: 'Software Development',
    description: 'Backend Developers architect the servers, databases, business logic, and security systems that power web applications behind the scenes.',
    beginnerSummary: 'You handle the engine room: storing data, processing transactions, securing passwords, and delivering APIs.',
    difficulty: 'Intermediate',
    mainSkills: ['Node.js or Python or Java', 'RESTful APIs', 'Relational Databases (PostgreSQL/MySQL)', 'Authentication & JWT', 'Data Structures & Caching'],
    technologies: ['Node.js', 'Express', 'Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'Prisma'],
    responsibilities: [
      'Design reliable and scalable server architecture',
      'Implement database schemas, migrations, and query indexing',
      'Build secure authentication, password encryption, and authorization systems',
      'Create and document clean RESTful or GraphQL API endpoints',
    ],
    beginnerReqs: ['Logical problem solving', 'Interest in data flow and backend structure'],
    roadmapShUrl: 'https://roadmap.sh/backend',
    isPopular: true,
  },
  {
    id: 'ai-engineer',
    slug: 'ai-engineer',
    courseSlug: 'aiml',
    title: 'AI / Machine Learning Engineer',
    domain: 'Data & AI',
    description: 'AI & ML Engineers build, train, and deploy artificial intelligence models, LLM systems, neural networks, and automated decision engines.',
    beginnerSummary: 'You teach computers how to learn from data, make predictions, understand language, and generate intelligent content.',
    difficulty: 'Advanced',
    mainSkills: ['Python Programming', 'Linear Algebra & Probability', 'NumPy, Pandas & Scikit-learn', 'PyTorch / TensorFlow', 'Prompt Engineering & LLMs', 'Model Deployment'],
    technologies: ['Python', 'PyTorch', 'Hugging Face', 'LangChain', 'OpenAI / Gemini API', 'FastAPI', 'Docker'],
    responsibilities: [
      'Collect, clean, and preprocess large datasets for model training',
      'Select and train machine learning and deep learning architectures',
      'Integrate Large Language Models (LLMs) with retrieval-augmented generation (RAG)',
      'Deploy and serve machine learning inference APIs at scale',
    ],
    beginnerReqs: ['Comfort with basic math (algebra/graphs)', 'Curiosity about algorithms and artificial intelligence'],
    roadmapShUrl: 'https://roadmap.sh/ai-data-scientist',
    isPopular: true,
  },
  {
    id: 'data-analyst',
    slug: 'data-analyst',
    courseSlug: 'cse',
    title: 'Data Analyst',
    domain: 'Data & AI',
    description: 'Data Analysts inspect, clean, transform, and model data to discover useful insights, build interactive dashboards, and drive business decisions.',
    beginnerSummary: 'You turn messy spreadsheets and databases into clear charts, stories, and recommendations that guide companies.',
    difficulty: 'Beginner',
    mainSkills: ['Excel / Google Sheets', 'SQL Queries & Joins', 'Power BI or Tableau', 'Python for Data Analysis (Pandas/Matplotlib)', 'Business Communication'],
    technologies: ['SQL', 'Power BI', 'Tableau', 'Python', 'Pandas', 'Excel', 'PostgreSQL'],
    responsibilities: [
      'Query relational databases using SQL to extract specific datasets',
      'Create interactive business dashboards for stakeholders',
      'Analyze trends, patterns, and anomalies in historical data',
      'Present findings through clear visual charts and actionable narratives',
    ],
    beginnerReqs: ['Analytical curiosity', 'Interest in spreadsheets, numbers, and visual charts'],
    roadmapShUrl: 'https://roadmap.sh/data-analyst',
    isPopular: true,
  },
  {
    id: 'devops-engineer',
    slug: 'devops-engineer',
    courseSlug: 'cse',
    title: 'DevOps & Cloud Engineer',
    domain: 'Cloud & DevOps',
    description: 'DevOps Engineers bridge software development and IT operations by automating deployments, managing cloud infrastructure, and ensuring 24/7 uptime.',
    beginnerSummary: 'You build the automated pipelines and cloud servers that keep software running reliably for millions of users.',
    difficulty: 'Intermediate',
    mainSkills: ['Linux & Bash Scripting', 'Git & CI/CD Pipelines', 'Docker & Containerization', 'Cloud Platforms (AWS/GCP)', 'Kubernetes Basics', 'Infrastructure as Code'],
    technologies: ['Linux', 'Docker', 'Kubernetes', 'GitHub Actions', 'AWS', 'Terraform', 'Nginx'],
    responsibilities: [
      'Automate code testing and continuous delivery pipelines',
      'Containerize applications with Docker for consistent runtime',
      'Provision and manage cloud infrastructure securely',
      'Monitor system health, error rates, and server performance',
    ],
    beginnerReqs: ['Curiosity for how cloud servers and deployment workflows operate'],
    roadmapShUrl: 'https://roadmap.sh/devops',
    isPopular: false,
  },
  {
    id: 'cybersecurity-analyst',
    slug: 'cybersecurity-analyst',
    courseSlug: 'it',
    title: 'Cybersecurity Analyst',
    domain: 'Cybersecurity',
    description: 'Cybersecurity Analysts protect networks, computer systems, and sensitive data from cyber attacks, vulnerabilities, and unauthorized access.',
    beginnerSummary: 'You act as a digital security guard, detecting attacks, securing servers, and fixing vulnerabilities before hackers can find them.',
    difficulty: 'Intermediate',
    mainSkills: ['Networking & Protocols (TCP/IP, DNS, HTTPS)', 'Linux Security', 'Vulnerability Assessment', 'Cryptography Basics', 'Security Information (SIEM)'],
    technologies: ['Wireshark', 'Nmap', 'Linux', 'Metasploit Basics', 'Burp Suite', 'Splunk'],
    responsibilities: [
      'Monitor organizational networks for security incidents and breaches',
      'Conduct vulnerability scans and recommend patches',
      'Enforce security best practices, firewalls, and access policies',
      'Investigate and document incident response forensics',
    ],
    beginnerReqs: ['Problem solving mindset', 'Strong interest in ethics, networks, and computer safety'],
    roadmapShUrl: 'https://roadmap.sh/cyber-security',
    isPopular: false,
  },
  {
    id: 'mobile-developer',
    slug: 'mobile-developer',
    courseSlug: 'bca',
    title: 'Mobile App Developer',
    domain: 'Mobile Development',
    description: 'Mobile App Developers create intuitive, smooth applications for smartphones and tablets running Android and iOS.',
    beginnerSummary: 'You build phone apps that users can download from Google Play and Apple App Store.',
    difficulty: 'Intermediate',
    mainSkills: ['React Native or Flutter or Kotlin', 'Mobile UI Design', 'State Management', 'REST API Integration', 'Offline Storage', 'App Store Publishing'],
    technologies: ['Flutter', 'React Native', 'Kotlin', 'Dart', 'Firebase', 'SQLite'],
    responsibilities: [
      'Develop touch-friendly, responsive mobile interfaces',
      'Connect mobile apps to cloud APIs and databases',
      'Manage offline storage, push notifications, and device hardware (camera, GPS)',
      'Package and publish releases to Google Play and Apple App Store',
    ],
    beginnerReqs: ['Smartphone user curious about how apps are constructed'],
    roadmapShUrl: 'https://roadmap.sh/android',
    isPopular: false,
  },
];

export const FULLSTACK_ROADMAP: RoadmapNode[] = [
  {
    id: 'fs-01',
    order: 1,
    title: 'Programming Fundamentals',
    summary: 'Master foundational computer science logic: variables, data types, conditionals, loops, functions, and algorithmic thinking.',
    beginnerSummary: 'Learn the basic building blocks of coding: how to store information, make decisions, and repeat tasks automatically.',
    whyNeedIt: 'Every single line of code you write will use variables, loops, and functions. Without these fundamentals, advanced frameworks feel confusing.',
    topics: ['Variables & Constants', 'Primitive Types (Strings, Numbers, Booleans)', 'Conditional Logic (if/else, switch)', 'Loops (for, while)', 'Functions & Parameters', 'Basic Problem Solving'],
    practiceTasks: [
      'Write a program that checks whether a student passed or failed based on marks',
      'Create a loop that prints the multiplication table of any number',
      'Write a function that calculates the total price including tax',
    ],
    projectIdea: 'Simple command-line calculator or student grade evaluator.',
    status: 'completed',
  },
  {
    id: 'fs-02',
    order: 2,
    title: 'HTML5 & CSS3 Essentials',
    summary: 'Build semantic web structure with HTML5 and style modern, responsive layouts using CSS3 Flexbox and CSS Grid.',
    beginnerSummary: 'HTML gives a web page its skeleton (text, buttons, images), and CSS gives it beauty, color, spacing, and mobile responsiveness.',
    whyNeedIt: 'Every web application in the world renders HTML and CSS. It is the visual layer every user sees and clicks.',
    topics: ['HTML5 Semantic Elements (header, nav, main, section, footer)', 'Forms & Inputs', 'CSS Box Model (margin, border, padding, content)', 'Flexbox Layouts', 'CSS Grid', 'Media Queries for Mobile Screens', 'Modern Tailwind CSS Basics'],
    practiceTasks: [
      'Code a multi-page personal portfolio with contact form',
      'Create a responsive 3-column pricing card layout that collapses on mobile screens',
      'Recreate a clean product showcase card using Tailwind CSS',
    ],
    projectIdea: 'A responsive personal developer portfolio website.',
    status: 'learning',
  },
  {
    id: 'fs-03',
    order: 3,
    title: 'JavaScript (Modern ES6+)',
    summary: 'Make web applications interactive: DOM manipulation, events, asynchronous programming, Promises, async/await, and Fetch API.',
    beginnerSummary: 'JavaScript breathes life into static pages. It handles button clicks, animations, popups, and talking to the server without refreshing.',
    whyNeedIt: 'JavaScript is the undisputed programming language of the web, running both in the browser and on the server with Node.js.',
    topics: ['Arrays & Array Methods (map, filter, reduce)', 'Objects & Destructuring', 'DOM Selection & Event Listeners', 'ES6 Modules (import/export)', 'Promises & Async/Await', 'Fetch API & JSON Parsing', 'Local Storage Basics'],
    practiceTasks: [
      'Build an interactive counter app with increment, decrement, and reset',
      'Create a filterable product list where typing in an input filters items instantly',
      'Fetch live data from a public weather or dog image API and display it dynamically',
    ],
    projectIdea: 'Interactive To-Do List app with localStorage persistence.',
    status: 'not_started',
  },
  {
    id: 'fs-04',
    order: 4,
    title: 'Git & GitHub Version Control',
    summary: 'Track code changes, collaborate with branches, commit history, pull requests, and host code on GitHub.',
    beginnerSummary: 'Git is like an "infinite undo" and time machine for your code. GitHub is where developers store and share their code with employers.',
    whyNeedIt: 'Professional engineering teams never work without Git. Your GitHub profile is also your live technical resume.',
    topics: ['Git Init, Add, Commit', 'Status & Log Inspection', 'Branches & Merging', 'Resolving Merge Conflicts', 'Pushing to GitHub', 'Pull Requests & Code Reviews', '.gitignore Best Practices'],
    practiceTasks: [
      'Initialize a git repository for your portfolio and make 5 meaningful commits',
      'Create a new feature branch, modify code, and merge it back into main',
      'Push your repository to GitHub and publish it live with GitHub Pages or Vercel',
    ],
    projectIdea: 'A live GitHub repository showcasing your practice mini-projects with clean README documentation.',
    status: 'not_started',
  },
  {
    id: 'fs-05',
    order: 5,
    title: 'Frontend Framework: React & Next.js',
    summary: 'Build scalable Single Page and Server-Rendered Applications with React components, hooks (useState, useEffect), props, and Next.js routing.',
    beginnerSummary: 'Instead of writing messy repetitive HTML, React lets you build reusable Lego-like components (Navbar, Card, Button) that update automatically.',
    whyNeedIt: 'React is the industry standard frontend technology requested in over 70% of modern web developer job openings.',
    topics: ['JSX Syntax', 'Functional Components & Props', 'useState for Dynamic Data', 'useEffect & Lifecycle', 'Component Composition', 'Next.js App Router & Pages', 'Client vs Server Components'],
    practiceTasks: [
      'Build a reusable Card component that accepts image, title, and badge props',
      'Create a search-and-filter dashboard in React fetching data from an API',
      'Build a multi-page app with Next.js App Router featuring dynamic routes',
    ],
    projectIdea: 'E-commerce product catalog with interactive cart and category filtering.',
    status: 'not_started',
  },
  {
    id: 'fs-06',
    order: 6,
    title: 'Backend Development & RESTful APIs',
    summary: 'Design server-side logic using Node.js & Express or Next.js API Route handlers, handling HTTP methods, middleware, and request/response lifecycles.',
    beginnerSummary: 'The backend is the brain of your application that lives on the server. It verifies user requests, processes data, and sends back clean answers.',
    whyNeedIt: 'Websites need a secure place to store accounts, process payments, and run confidential logic that cannot be manipulated in the browser.',
    topics: ['HTTP Methods (GET, POST, PUT, DELETE)', 'Request Body & URL Parameters', 'Building Express or Next.js Route Handlers', 'Middleware & Error Handling', 'CORS & Security Headers', 'Input Validation with Zod'],
    practiceTasks: [
      'Build a simple REST API with endpoints to get, create, and delete notes',
      'Create a validation middleware that rejects invalid email or missing fields',
      'Test your API endpoints using Postman or Thunder Client',
    ],
    projectIdea: 'Student Book Exchange REST API with full CRUD endpoints.',
    status: 'not_started',
  },
  {
    id: 'fs-07',
    order: 7,
    title: 'Databases: PostgreSQL & SQL',
    summary: 'Model relational schemas, write queries, manage primary/foreign keys, joins, indexes, and integrate ORMs like Prisma or InsForge BaaS.',
    beginnerSummary: 'A database is a fast, structured, permanent digital filing cabinet where your app securely saves user accounts, posts, and orders.',
    whyNeedIt: 'Without a database, all your user data disappears the moment you close the browser or restart the server.',
    topics: ['Tables, Columns, Primary & Foreign Keys', 'SQL Queries (SELECT, INSERT, UPDATE, DELETE)', 'Filtering with WHERE & Sorting with ORDER BY', 'JOIN operations across multiple tables', 'Database Migrations', 'Connecting via InsForge / PostgreSQL'],
    practiceTasks: [
      'Design a database schema for a student course registration system',
      'Write SQL queries to find the top 5 students with the highest GPA',
      'Connect your backend API to InsForge PostgreSQL to store live records',
    ],
    projectIdea: 'Database-backed inventory tracking application.',
    status: 'not_started',
  },
  {
    id: 'fs-08',
    order: 8,
    title: 'Authentication & Security',
    summary: 'Implement secure user authentication, password hashing, JWT sessions, role-based authorization, and protected routes.',
    beginnerSummary: 'Allow users to sign up, log in securely with passwords, and ensure each student only views and edits their own private data.',
    whyNeedIt: 'Security is mandatory. Storing plain passwords or leaving endpoints unprotected can cause catastrophic data leaks.',
    topics: ['Password Hashing with bcrypt', 'JWT (JSON Web Tokens) & Sessions', 'Protected API Routes', 'Role-Based Access Control (Student vs Admin)', 'Securing Environment Variables (.env)', 'CORS, CSRF, and SQL Injection Prevention'],
    practiceTasks: [
      'Build a secure user registration flow with hashed passwords',
      'Protect a /dashboard route so only logged-in users can view it',
      'Implement a role check that restricts admin actions to authorized accounts',
    ],
    projectIdea: 'Secure user login portal with profile management and password reset.',
    status: 'not_started',
  },
  {
    id: 'fs-09',
    order: 9,
    title: 'Deployment, Cloud & CI/CD',
    summary: 'Deploy frontend and backend applications to production platforms (Vercel, InsForge, Render), configure environment variables, custom domains, and SSL.',
    beginnerSummary: 'Take your project off your personal laptop and launch it onto the real World Wide Web with a public link anyone can visit.',
    whyNeedIt: 'A project that only runs on your laptop cannot be shared with recruiters, clients, or friends.',
    topics: ['Production Builds & Optimization', 'Deploying to Vercel / InsForge', 'Environment Variables in Production', 'Custom Domains & HTTPS / SSL', 'Database Connection Pooling', 'Basic CI/CD Automated Checks'],
    practiceTasks: [
      'Deploy your full-stack project to Vercel with live environment keys',
      'Configure production database connections on InsForge',
      'Run Lighthouse audit to score 90+ on performance and SEO',
    ],
    projectIdea: 'Production deployment of your capstone full-stack web application.',
    status: 'not_started',
  },
  {
    id: 'fs-10',
    order: 10,
    title: 'Job Preparation & Software Interviews',
    summary: 'Prepare for software engineer placement interviews: Data Structures & Algorithms, System Design fundamentals, resume optimization, and mock interviews.',
    beginnerSummary: 'Get hired! Polish your resume, practice common coding questions, showcase your portfolio, and practice answering technical questions clearly.',
    whyNeedIt: 'Technical knowledge must be demonstrated during hiring tests and interviews to secure internships and full-time software engineering roles.',
    topics: ['DSA Core (Arrays, Strings, HashMaps, Linked Lists, Trees)', 'Time & Space Complexity (Big O Notation)', 'Resume Crafting with STAR method', 'GitHub Portfolio Polishing', 'Behavioral Interview Questions ("Tell me about a time...")', 'Technical System Walkthroughs'],
    practiceTasks: [
      'Solve 25 beginner LeetCode / HackerRank problems (Arrays & HashMaps)',
      'Format a one-page ATS-friendly resume highlighting 2 full-stack projects',
      'Conduct a mock interview explaining how your database and API communicate',
    ],
    projectIdea: 'Complete ATS-optimized portfolio site with live project demos and case studies.',
    status: 'not_started',
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'proj-01',
    title: 'Personal Developer Portfolio & Resume',
    careerSlug: 'frontend-developer',
    difficulty: 'Beginner',
    description: 'A clean, modern, responsive developer portfolio showcasing your skills, bio, featured projects with live demo links, and a working contact form.',
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'Tailwind CSS'],
    skillsLearned: ['Semantic HTML', 'Mobile-first responsive design', 'CSS Flexbox/Grid', 'DOM manipulation', 'Deployment on Vercel/GitHub Pages'],
    estimatedTime: '8 - 12 hours',
    features: [
      'Hero banner with introduction and profile photo',
      'Skills grid highlighting technologies known',
      'Projects section with tags and GitHub links',
      'Interactive dark/light theme switch',
      'Working contact form with validation',
    ],
    extensions: [
      'Add a downloadable PDF resume button',
      'Integrate EmailJS or formspree to receive real emails',
      'Add subtle scroll animations',
    ],
  },
  {
    id: 'proj-02',
    title: 'Smart Task & Study Habit Tracker',
    careerSlug: 'frontend-developer',
    difficulty: 'Beginner',
    description: 'An interactive productivity application to organize daily study schedules, checklist tasks, categorize by priority, and store progress locally.',
    technologies: ['JavaScript / React', 'Tailwind CSS', 'Local Storage'],
    skillsLearned: ['State management', 'CRUD operations', 'Local storage persistence', 'Form handling', 'Filter & search logic'],
    estimatedTime: '10 - 15 hours',
    features: [
      'Add, edit, delete, and check off study tasks',
      'Filter tasks by All, Active, and Completed',
      'Priority tags (High, Medium, Low) with colored badges',
      'Persist all tasks across browser refreshes with localStorage',
    ],
    extensions: [
      'Add a Pomodoro study timer with audio chime',
      'Weekly completion streak counter',
      'Export tasks to JSON or CSV',
    ],
  },
  {
    id: 'proj-03',
    title: 'Interactive Weather & Campus Forecast App',
    careerSlug: 'frontend-developer',
    difficulty: 'Beginner',
    description: 'Real-time weather application consuming a third-party weather API (OpenWeatherMap) to show live temperature, forecasts, wind, and conditions for any city.',
    technologies: ['React', 'Next.js', 'Fetch API', 'Tailwind CSS'],
    skillsLearned: ['Consuming third-party REST APIs', 'Async/await error handling', 'Dynamic icons based on weather condition', 'Geolocation API'],
    estimatedTime: '12 - 16 hours',
    features: [
      'Search weather by city name with autocomplete',
      'Display 5-day weather forecast cards',
      'Automatic geolocation button for local temperature',
      'Smooth loading skeletons while data is being fetched',
    ],
    extensions: [
      'Add animated weather backgrounds (rain, sunny, clouds)',
      'Hourly temperature trend chart',
    ],
  },
  {
    id: 'proj-04',
    title: 'Student Course & Notes Management Hub',
    careerSlug: 'full-stack-developer',
    difficulty: 'Intermediate',
    description: 'A full-stack web application where college students can organize their semester subjects, upload markdown notes, search topics, and track semester deadlines.',
    technologies: ['Next.js', 'TypeScript', 'PostgreSQL / InsForge', 'Tailwind CSS'],
    skillsLearned: ['Full-stack CRUD architecture', 'Relational database schema modeling', 'Markdown rendering', 'Search indexing'],
    estimatedTime: '25 - 35 hours',
    features: [
      'Semester and subject categorizer',
      'Rich markdown editor for taking class notes',
      'Fast full-text search across all saved notes',
      'Assignment deadline calendar with status badges',
    ],
    extensions: [
      'Share note links with classmates via public read-only URLs',
      'Export notes directly to PDF',
    ],
  },
  {
    id: 'proj-05',
    title: 'Campus Tech Job & Internship Board',
    careerSlug: 'full-stack-developer',
    difficulty: 'Intermediate',
    description: 'A dedicated job portal connecting college students with tech internships, junior developer listings, filterable by skill, remote/on-site, and stipend.',
    technologies: ['Next.js', 'PostgreSQL / InsForge', 'Tailwind CSS', 'Zod'],
    skillsLearned: ['Multi-table database queries', 'Advanced filtering and pagination', 'Form validation with Zod', 'Authentication & authorization'],
    estimatedTime: '30 - 40 hours',
    features: [
      'Listing feed with filters for role type, location, and salary',
      'Detailed job overview page with requirements and apply button',
      'Student profile with uploaded resume link and applied jobs list',
      'Admin portal to post, edit, and approve job postings',
    ],
    extensions: [
      'Email notifications when new internships matching student skills are posted',
      'Bookmark and save listings for later',
    ],
  },
  {
    id: 'proj-06',
    title: 'AI-Powered Study Flashcards & Quiz Generator',
    careerSlug: 'ai-engineer',
    difficulty: 'Intermediate',
    description: 'An intelligent study helper where students paste class lecture notes and an AI model automatically generates structured flashcards and multiple-choice quizzes.',
    technologies: ['Next.js', 'Python / Node.js', 'OpenAI / OpenRouter API', 'PostgreSQL'],
    skillsLearned: ['Prompt engineering', 'Structured JSON output from AI models', 'Flashcard review algorithms (Spaced Repetition)', 'Score tracking'],
    estimatedTime: '25 - 35 hours',
    features: [
      'Paste textbook or lecture notes up to 3,000 words',
      'AI automatically generates 10 flashcards with question and concise answer',
      'Interactive flip-card study mode',
      'Multiple-choice quiz mode with instant scoring and explanations',
    ],
    extensions: [
      'Spaced repetition algorithm to resurface difficult cards',
      'Export flashcard deck to Anki format',
    ],
  },
  {
    id: 'proj-07',
    title: 'Real-Time Collaborative Code & Chat Room',
    careerSlug: 'full-stack-developer',
    difficulty: 'Advanced',
    description: 'A real-time web application where multiple students can join a virtual study room, chat in real time, and edit code snippets simultaneously.',
    technologies: ['Next.js', 'WebSockets / Realtime', 'Monaco Code Editor', 'PostgreSQL'],
    skillsLearned: ['WebSocket protocols and pub/sub architecture', 'Concurrency and state synchronization', 'Monaco editor integration', 'Production scaling'],
    estimatedTime: '40 - 55 hours',
    features: [
      'Room-based authentication and unique join codes',
      'Real-time chat with presence indicators (who is currently online)',
      'Multi-language syntax highlighted code editor with live sync',
      'Built-in code runner executing JavaScript or Python output',
    ],
    extensions: [
      'Voice chat rooms using WebRTC',
      'Save room session transcripts and code history',
    ],
  },
];

export const RESOURCES: Resource[] = [
  {
    id: 'res-01',
    skillTag: 'JavaScript',
    title: 'MDN Web Docs: JavaScript Guide',
    type: 'Documentation',
    level: 'Beginner',
    duration: 'Self-paced',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide',
    isFree: true,
    provider: 'Mozilla Developer Network',
  },
  {
    id: 'res-02',
    skillTag: 'JavaScript',
    title: 'JavaScript.info: Modern JavaScript Tutorial',
    type: 'Course',
    level: 'Beginner',
    duration: '20 hours',
    url: 'https://javascript.info/',
    isFree: true,
    provider: 'JavaScript.info',
  },
  {
    id: 'res-03',
    skillTag: 'React',
    title: 'Official React Documentation & Quick Start',
    type: 'Documentation',
    level: 'Beginner',
    duration: '8 hours',
    url: 'https://react.dev/learn',
    isFree: true,
    provider: 'React.dev',
  },
  {
    id: 'res-04',
    skillTag: 'Full Stack',
    title: 'Full Stack Open - University of Helsinki',
    type: 'Course',
    level: 'Intermediate',
    duration: '60 hours',
    url: 'https://fullstackopen.com/en/',
    isFree: true,
    provider: 'University of Helsinki',
  },
  {
    id: 'res-05',
    skillTag: 'Databases',
    title: 'PostgreSQL Tutorial for Beginners',
    type: 'Course',
    level: 'Beginner',
    duration: '10 hours',
    url: 'https://www.postgresqltutorial.com/',
    isFree: true,
    provider: 'PostgreSQL Tutorial',
  },
  {
    id: 'res-06',
    skillTag: 'Git',
    title: 'Learn Git Branching (Interactive Visual Game)',
    type: 'Practice',
    level: 'Beginner',
    duration: '4 hours',
    url: 'https://learngitbranching.js.org/',
    isFree: true,
    provider: 'LearnGitBranching',
  },
  {
    id: 'res-07',
    skillTag: 'Python & AI',
    title: 'Python for Everybody Specialization',
    type: 'Course',
    level: 'Beginner',
    duration: '30 hours',
    url: 'https://www.py4e.com/',
    isFree: true,
    provider: 'Dr. Chuck / PY4E',
  },
  {
    id: 'res-08',
    skillTag: 'Data Structures',
    title: 'NeetCode Roadmap & Beginner DSA',
    type: 'Practice',
    level: 'Intermediate',
    duration: '40 hours',
    url: 'https://neetcode.io/roadmap',
    isFree: true,
    provider: 'NeetCode.io',
  },
  {
    id: 'res-09',
    skillTag: 'Roadmaps',
    title: 'roadmap.sh Community Developer Roadmaps',
    type: 'Documentation',
    level: 'Beginner',
    duration: 'Ongoing',
    url: 'https://roadmap.sh',
    isFree: true,
    provider: 'roadmap.sh',
  },
];

export const INITIAL_STUDY_PLAN: StudyTask[] = [
  { id: 'st-1', day: 'Monday', topic: 'JavaScript Fundamentals & Array Methods', durationHours: 1.5, completed: true },
  { id: 'st-2', day: 'Tuesday', topic: 'Data Structures: Arrays & HashMaps on LeetCode', durationHours: 1.0, completed: true },
  { id: 'st-3', day: 'Wednesday', topic: 'React Components & useState Hook', durationHours: 1.5, completed: false },
  { id: 'st-4', day: 'Thursday', topic: 'SQL Queries & InsForge Database Schema Modeling', durationHours: 1.0, completed: false },
  { id: 'st-5', day: 'Friday', topic: 'Hands-on Project Work: Building Student Hub', durationHours: 2.0, completed: false },
  { id: 'st-6', day: 'Saturday', topic: 'DSA Practice & Mock Coding Interview Problems', durationHours: 2.0, completed: false },
  { id: 'st-7', day: 'Sunday', topic: 'Weekly Code Revision & GitHub Commit Review', durationHours: 1.0, completed: false },
];

export const ACHIEVEMENTS: Achievement[] = [
  { id: 'ach-1', key: 'first_roadmap', title: 'Roadmap Explorer', description: 'Started your first career roadmap', icon: '🗺️', unlocked: true, unlockedAt: '2 days ago' },
  { id: 'ach-2', key: 'first_node', title: 'First Milestone', description: 'Completed your first roadmap milestone', icon: '🎯', unlocked: true, unlockedAt: 'Yesterday' },
  { id: 'ach-3', key: 'three_skills', title: 'Skill Builder', description: 'Learned 3 fundamental technical skills', icon: '⭐', unlocked: false },
  { id: 'ach-4', key: 'first_project', title: 'Project Creator', description: 'Started your first portfolio project', icon: '🚀', unlocked: false },
  { id: 'ach-5', key: 'study_streak', title: 'Consistency Master', description: 'Maintained a 7-day study streak', icon: '🔥', unlocked: true, unlockedAt: 'Today' },
];
